name: newsletter_client_actions
on: [push]
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Install libraries
        run: npm install --only=dev
      - 
        name: Run ESLint
        run: npm run lint